### ISSUE TITLE
Hexo 6 support

### ISSUE THREAD

**Issue by appotry** [sergeyzwezdin/hexo-feed#4]
```
# npm install hexo-feed --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hexo-site@0.0.0
npm ERR! Found: hexo@6.1.0
npm ERR! node_modules/hexo
npm ERR!   hexo@"^6.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer hexo@"^4.2.0 || ^5.2.0" from hexo-feed@1.1.0
npm ERR! node_modules/hexo-feed
npm ERR!   dev hexo-feed@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by sergeyzwezdin** [comment]
@appotry  Correct, currently the plugin support only 4&5 versions. I didn't test it with Hexo 6 and do not have enough time right now. If you want, please create PR for updating it.

**Comment by appotry** [comment]
> sergeyzwezdin

I have tested it on hexo 6.1.  It  works fine！  

On [my blog ](https://blog.17lai.site)， 
![](https://cdn.jsdelivr.net/gh/appotry/cloudimg@latest/data/2022/03/2720220327072844.png)

So, you can add hexo 6.x version support ！

**Comment by appotry** [comment]
@sergeyzwezdin  tested well.  

and  i make a pr

**Comment by appotry** [comment]
@sergeyzwezdin what about pr https://github.com/sergeyzwezdin/hexo-feed/pull/5 ?

**Comment by sergeyzwezdin** [comment]
@appotry done
